### ISSUE TITLE
[feature] Write the logged user in the database with the right status

### ISSUE THREAD

**Issue by syu93** [pinnackl/photos-contest-fb#4]
Write the logged use in the database with the right status

**Comment by athorel** [comment]
write user in database at his first connection

**Comment by athorel** [comment]
to be tested

**Comment by syu93** [comment]
Check if the user is already registered in the database before writing it

**Comment by syu93** [comment]
Keep in mind that the user status depends on the date he register in.
**For example** :
If the contest last two days. The first day is for registration, so the user will be registered as participant, and the second day as voters

**Comment by athorel** [comment]
On login I just checked if the user is already registered by comparing his email. I write in database only the first time the user is connected to the app (default role = participant). I don't need to check his role I guess.

**Comment by syu93** [comment]
We get the right status and contest ID

See : #18 

We need to be able to update the user later for registering another contest
